name: ESLint

on:
  pull_request:
    paths:
      - '**.ts'
      - '.eslintrc.js'
      - 'pnpm-lock.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run ESLint
      run: pnpm run lint
